# Generated by Django 3.2 on 2021-06-01 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('descrp', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 15, 6, 47, 859683))),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('descr', models.TextField(blank=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 15, 6, 47, 812803))),
                ('cmplte', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 15, 6, 47, 863670))),
                ('project', models.ManyToManyField(to='gestionprojet.Project')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(to='gestionprojet.Task'),
        ),
    ]
