# Generated by Django 3.2 on 2021-06-01 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestionprojet', '0002_auto_20210601_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 7, 12, 744955)),
        ),
        migrations.AlterField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(blank=True, null=True, to='gestionprojet.Task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 7, 12, 697080)),
        ),
        migrations.AlterField(
            model_name='user',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 1, 16, 7, 12, 748943)),
        ),
        migrations.AlterField(
            model_name='user',
            name='project',
            field=models.ManyToManyField(blank=True, null=True, to='gestionprojet.Project'),
        ),
    ]
